version: "3.8"

services:
  worker:
    build:
      context: ../app
      dockerfile: ../env/worker.Dockerfile
    volumes:
      - ../app:/var/www/app
    restart: always
    networks:
      - shared_net

  nginx:
    image: nginx:1.19
    ports:
      - "8000:80"
    volumes:
      - ../app/public:/var/www/html
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - worker
    restart: always
    networks:
      - shared_net

  sqlite-db:
    image: keinos/sqlite3
    volumes:
      - ../app/database:/root/db
    restart: always
    networks:
      - shared_net

networks:
  shared_net:
